### PR TITLE
[FIX] Workflows page alignment

### LINKED ISSUE #81: Blog and workflows pages are needlessly narrow
The page with blogs and with workflows have large margins on the sides. The content is narrower than the menu (especially problematic on small browser windows). The content should be aligned with the menu width.

Also, when the window is small, the title currently gets hidden under the glasses.

### PR DESCRIPTION
**Pull request by mitjapotocin**
Fixes #81 

* Workflow page now has the same margin from navigation bar on all screen sizes.
* Fixed workflow page alignment. Text is aligned with navigation bar logo. 
* Changed container to auto expand up to 1200px wide screens.  Container width is capped at 1200px on wider size screens.

### CODE REVIEW

**Comment by markotoplak** [comment]
Thank you, looks much better.

Did you notice that the fonts on your version of the page changed? Can we have the old ones back? :)

Also, could you change the blog page in the same way? It had a very similar structure before.

**Comment by mitjapotocin** [comment]
I will try to find those fonts 😀

I was planning on working on the blog page next. 

Do you like the container being capped at 1200px?

I also noticed, that search doesn’t work on workflows page, and clicking on tags results in some strange behavior.

**Comment by markotoplak** [comment]
About container size: I do not quite understand the reason the change to 1200. Wasn't it 1170 originally? For 30 pixels I'd rather leave it, but if you have a reason, I do not see a problem. 

Oh, well, we would also have to fix the search then. Thanks for finding out about it.

**Comment by mitjapotocin** [comment]
Before it was downsized to 1170px @1200px screen width and container had no padding. 
Now it is capped at 1200px @1200px screen width and container has 30px padding, so it is the same as before. 

The main difference is, that the container is not downdized up to 1200px screen width, as it was before.

**Comment by mitjapotocin** [comment]
• I have fixed blog page alignment.
• I have made blog content narrower (max 630px) for easier reading. And I am opened for suggestions about blog content width.

**Comment by markotoplak** [comment]
Thanks.

Look what happens when mouse is connected to my Mac with Chrome (OS X, by default, only renders scroll bars separately if mouse is connected - otherwise they are drawn on top of the content).

image

The bottom scroll bar appears only if the window size is a bit more that 1200. I thought it is connected to your change of container size, but the current page also has the same issue.

**Comment by mitjapotocin** [comment]
There must be some overflow than. I will fix it.

**Pull request merged**
