### PR TITLE
Search reorganise

### PR DESCRIPTION
**Pull request by andraz213**
Moving search to a separate site to improve user experience and code maintainability.

### CODE REVIEW

**Comment by irgolic** [comment]
Hey, thanks for this :D

Summing up our conversation, this is TODO:
- [ ] Remove blog categories from search
- [ ] Inline search (discourage visiting empty search page)
- [ ] Click on link -> back should keep results
- [ ] Show more shouldn't appear when there’s nothing more to show

**Comment by ajdapretnar** [comment]
> Remove blog categories from search

@irgolic What does this entail?

**Comment by irgolic** [comment]
The category itself appears as a search result, not under just next to a blog.

E.g. search 'download'

Screenshot 2021-03-10 at 23 38 08

The first result takes you to /blog/download, which cname-redirects to /blog.

**Comment by ajdapretnar** [comment]
Ah ok, so no major changes to the handling of categories. Thanks!

**Pull request merged**
