### PR TITLE
Add gallery for blog images & side thumbnails.

### PR DESCRIPTION
**Pull request by NejcDebevec**
Add gallery for blog images & side thumbnails. @janezd @ajdapretnar

### CODE REVIEW

**Comment by ajdapretnar** [comment]
This removes the space between images that was introduced in https://github.com/biolab/orange-hugo/pull/115 (vertical padding for images). Please add back (it was real nice).

**Comment by ajdapretnar** [comment]
The rest is great and we can merge after the space is added.

**Comment by ajdapretnar** [comment]
Ok, gallery view is great. Side thumbnails.... They confuse the hell out of me. They are so small they look like a glitch. On small screens (phone), they fall out of view almost completely. @janezd please keep in mind that not everyone reads blogs with extra white space on the side.
I don't like the thumbnails very much. Still in favor of workflows + widget, side by side.

**Comment by NejcDebevec** [comment]
> Ok, gallery view is great. Side thumbnails.... They confuse the hell out of me. They are so small they look like a glitch. On small screens (phone), they fall out of view almost completely. @janezd please keep in mind that not everyone reads blogs with extra white space on the side.
> I don't like the thumbnails very much. Still in favor of workflows + widget, side by side.

What about if we add does images like word links and if you click on the word it will open image=

**Pull request merged**
