### PR TITLE
[FIX] Horizontal scrollbar appearing

### PR DESCRIPTION
**Pull request by mitjapotocin**

### CODE REVIEW

**Comment by markotoplak** [comment]
So how did you figure out what difference you need? 1185 vs 1170 compared to 1200 vs 1170 as it was originally? I am interested to learn your reasoning behind this.

**Comment by mitjapotocin** [comment]
It puzzles me to. 
1200 vs 1170 makes more sense, but when I tried it, there was a jump in container width, when browser width was at 1200.
With 1185 vs 1170 the transition from width auto, to fixed is smooth, while resizing the window.

**Comment by mitjapotocin** [comment]
I found out. 
If you use @media(max-width), max-width includes scrollbar. 
Scrollbar is usually 17px wide, but just to be safe it is recommended using 20px difference. 
So 1190px vs 1170px should work, with just a small jump in container width, when reacting 1190px wide window.

**Comment by markotoplak** [comment]
Works nicely!

**Pull request merged**
