### PR TITLE
Fix for newer hugo versions

### LINKED ISSUE #150: Migrate page to support a higher version of hugo
Currently the website is built on hugo 0.49.2. Latest version is 0.70.0, which break some functionalities. Rewrite the page to run on the latest hugo.

### PR DESCRIPTION
**Pull request by markotoplak**
@ajdapretnar, does this fix #150?

### CODE REVIEW

**Comment by ajdapretnar** [comment]
I don't see a built site with this. Just blank. Also, we sure we want to go with unsafe=True? 😅

**Comment by markotoplak** [comment]
Yes, we definitely want to go with unsafe=True here, because in Hugo 0.60 they changed the behaviour of interpreting markdown differently. Now they disallow embedded html. Unsafe=true gets the old behaviour. I think we are using embedded html in places.

**Comment by irgolic** [comment]
I also get a blank page. Both on master and this PR, with hugo versions 0.69 and 0.72.

**Comment by markotoplak** [comment]
I admit I only tried with 0.63.2. And I am quite surprised that backward compatibility breaks so often there. I'll try to fix the page for the current version.

**Comment by markotoplak** [comment]
@irgolic, @ajdapretnar, could you confirm that it works for you now?

**Comment by markotoplak** [comment]
@irgolic, @ajdapretnar, can you quickly try this one and merge if it works for you now?

**Comment by ajdapretnar** [comment]
Perfect! It works for me.

**Comment by irgolic** [comment]
Works like a charm, thanks. 👍

**Pull request merged**
